version: '2.1'
services:

  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -rejoin
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
    environment:
      GOMAXPROCS: "4"
    labels:
      com.max.service: "consul"
      com.max.version: "latest"
      com.max.namespace: "go-land"
    mem_limit: 128m

  user-service-1:
    image: go-land/user-service:1.0.0
    ports:
    - "9090:8080"
    environment:
      MICRO_SERVER_ADDRESS: ":8080"
      #      MICRO_REGISTRY: "mdns"
      CONSUL_PORT: "8500"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
    depends_on:
    - consul
    mem_limit: 128m

  user-service-2:
    image: go-land/user-service:1.0.0
    ports:
    - "9091:8080"
    environment:
      MICRO_SERVER_ADDRESS: ":8080"
      #      MICRO_REGISTRY: "mdns"
      CONSUL_PORT: "8500"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
    depends_on:
    - consul
    mem_limit: 128m

  job-service:
    image: go-land/job-service:1.0.0
    ports:
    - "7070:8080"
    environment:
      MICRO_SERVER_ADDRESS: ":8080"
      CONSUL_PORT: "8500"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
    depends_on:
    - consul
    mem_limit: 128m

  user-cli:
    image: go-land/user-cli:1.0.0
    environment:
      CONSUL_PORT: "8500"
      MICRO_REGISTRY_ADDRESS: "consul:8500"
    #      MICRO_REGISTRY: "mdns"
    labels:
      com.max.service: "user-cli"
      com.max.version: "1.0.0"
      com.max.namespace: "go-land"
    depends_on:
    - consul
    - user-service-1
    - user-service-2
    mem_limit: 128m
